### ISSUE TITLE
Search doesn't seem to work

### ISSUE THREAD

**Issue by Kixunil** [ccgauche/ytermusic#31]
I set up the headers according to the instructions, ran ytermusic, pressed `f`, entered a search term, pressed enter. Nothing happened, no error message printed. Am I supposed to press something else?

**Comment by ccgauche** [comment]
@Kixunil You aren't doing anything wrong. The search results should update maybe few seconds (like 5 max) after the last key stroke no action required.
Maybe send the logs.
Here what you should see:
![image](https://user-images.githubusercontent.com/16625987/204252440-6decb636-fcb7-4285-841f-abf5e6c5f44e.png)

**Comment by ccgauche** [comment]
It seems like your cookies are invalid it looks like the invalid page is the Google sign-in form. Have you correctly setup your cookies ?
Anyways I need to add a check for invalid cookies

**Comment by Kixunil** [comment]
Oh, do I need to sign in? Does the cookie give whole-account permission rather than youtube music only?

**Comment by ccgauche** [comment]
I only gives youtube music permission and is only on the client side (never
shared). It is necessary to use the app since access to the public API is
restricted using cookies. I could enable one time cookies generation for
people that aren't logged in but it would be a lot of work.

Le lun. 28 nov. 2022, 20:27, Martin Habovštiak ***@***.***> a
écrit :

**Comment by Kixunil** [comment]
Oh, wanted to say I finally got to try it again yesterday and it now works fine, especially the new version. Thanks a lot for everything!
