### ISSUE TITLE
Cookie-related issue

### ISSUE THREAD

**Issue by MarkhorDev** [ccgauche/ytermusic#57]
So I just discovered this project and it seems really cool. Unfortunately, I can't seem to get it working. 

When starting up the program, I cannot search for playlists or anything, and the log file has an InvalidHTMLFile error at the bottom, followed by a large amount of text.

Regarding the cookie, the readme says "Find the request to the music.youtube.com...", but there are so many requests that I am a bit confused about which one I should use. I have tried POST, GET, and HEAD requests, and I am only looking at OK responses. I have copied the cookie to the headers file and added a user agent. I am certain the issue is from the cookie and not the user agent.

I am using the 'alpha-0.0.10' release as the most recent doesn't have an exe so I couldn't get it running.

I have looked at issues to see if anyone else is having/has had a similar issue, and none of the suggested fixes are working. 

Any help would be appreciated!

**Comment by ccgauche** [comment]
Maybe the explanation isn't the greatest. Here what I recommend to do it correctly:
 - Open dev tools on an empty tab
 - Go to music.youtube.com
 - Take the first request and go to headers (the sent ones)
![image](https://github.com/ccgauche/ytermusic/assets/16625987/fd1f8c93-55fe-4436-8ae1-820ecbf2788d)
  - Go in raw mode and copy the lines with user-agent and cookies
  - You are good to go (If this still doesn't work I'll try a workaround)
 For the new version, I can't build one without a windows system due to some requirements on the lib side. Since I don't have my windows PC on hand, I can't build it this week but next week should be fine

**Comment by MarkhorDev** [comment]
Thank you for the clearer instructions, but it is still not working. The same error is in the log file. Could it be that current cookies don't work with the older version of ytermusic?

**Comment by ccgauche** [comment]
It is definitely possible. I don't really remember if there were a breakable on the youtube side between versions but you could maybe build it from source. I'm just gonna check if it works on my side

**Comment by MarkhorDev** [comment]
Sorry for the late reply. After building the latest release from source and getting a new cookie, things seem to be working fine. A few songs are failing to download, but I assume this is normal. Thanks for your help!
